[package]
name = "shasper"
version = "0.9.0"
authors = ["Parity Technologies <admin@parity.io>"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "shasper"
path = "src/main.rs"

[dependencies]
error-chain = "0.12"
futures = "0.1"
ctrlc = { version = "3.0", features = ["termination"] }
log = "0.4"
tokio = "0.1.7"
exit-future = "0.1"
parking_lot = "0.4"
hex-literal = "0.1"
slog = "^2"
parity-codec = { version = "3.0" }
trie-root = { version = "0.9" }
runtime-io = { package = "sr-io", git = "https://github.com/paritytech/substrate" }
runtime-primitives = { package = "sr-primitives", git = "https://github.com/paritytech/substrate" }
substrate-primitives = { git = "https://github.com/paritytech/substrate" }
cli = { package = "substrate-cli", git = "https://github.com/paritytech/substrate" }
executor = { package = "substrate-executor", git = "https://github.com/paritytech/substrate" }
service = { package = "substrate-service", git = "https://github.com/paritytech/substrate" }
transaction-pool = { package = "substrate-transaction-pool", git = "https://github.com/paritytech/substrate" }
network = { package = "substrate-network", git = "https://github.com/paritytech/substrate" }
client = { package = "substrate-client", git = "https://github.com/paritytech/substrate", default-features = false }
state-machine = { package = "substrate-state-machine", git = "https://github.com/paritytech/substrate" }
consensus = { package = "shasper-consensus", path = "consensus" }
primitives = { package = "shasper-primitives", path = "primitives" }
runtime = { package = "shasper-runtime", path = "runtime" }
crypto = { package = "shasper-crypto", path = "crypto" }
structopt = "0.2.13"
basic-authorship = { package = "substrate-basic-authorship", git = "https://github.com/paritytech/substrate" }
inherents = { package = "substrate-inherents", git = "https://github.com/paritytech/substrate" }
casper = { path = "casper" }

[build-dependencies]
vergen = "2"

[workspace]
members = [
	"runtime",
	"primitives",
	"consensus",
	"crypto",
	"casper",
	"beacon",
	"yamltests",
	"util/ssz",
	"util/ssz-derive",
	"util/keccak-hasher",
]
exclude = [
	"runtime/wasm",
]

[profile.release]
# Substrate runtime requires unwinding.
panic = "unwind"
