[package]
name = "transitiontests"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_yaml = "0.8"
clap = "2.32"
ssz = { path = "../../utils/ssz" }
beacon = { path = "../../beacon" }
crypto = { package = "shasper-crypto", path = "../../crypto" }
