[package]
name = "beacon"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"

[dependencies]
primitive-types = { version = "0.2", default-features = false }
hash-db = { version = "0.11", default-features = false }
tiny-keccak = "1.4.2"
plain_hasher = { version = "0.2", default-features = false }
impl-serde = { version = "0.1", optional = true }
serde = { version = "1.0", optional = true }
serde_derive = { version = "1.0", optional = true }
ssz = { version = "0.1.1", path = "../util/ssz", default-features = false }
ssz-derive = { version = "0.1.1", path = "../util/ssz-derive" }
fixed-hash = { version = "0.3.0", default-features = false }
parity-codec = { version = "3.2", default-features = false, optional = true, features = ["derive"] }

[features]
default = ["std", "with-serde", "with-codec"]
with-serde = [
	"serde",
	"serde_derive",
	"impl-serde",
	"std",
	"primitive-types/serde",
]
with-codec = [
	"parity-codec",
	"primitive-types/codec",
]
std-with-codec = [
	"parity-codec",
	"primitive-types/codec",
	"parity-codec/std",
]
std = [
	"ssz/std",
	"hash-db/std",
	"plain_hasher/std",
	"primitive-types/std",
	"fixed-hash/std",
]
