[package]
name = "ssz"
version = "0.1.0"
authors = ["Paul Hauner <paul@paulhauner.com>", "Parity Team <admin@parity.io>"]
license = "GPL-2.0"
license-file = "LICENSE"

[dependencies]
substrate-primitives = { git = "https://github.com/paritytech/substrate", default-features = false }
arrayvec = { version = "0.4", default_features = false }

[features]
default = ["std"]
std = [
	"substrate-primitives/std",
	"arrayvec/std",
]
